# Generated by Django 3.1.2 on 2021-03-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passenger_seat_booking_trains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trains',
            old_name='compartments',
            new_name='compartment_capacity',
        ),
    ]
