# Generated by Django 3.1.2 on 2021-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='arrival',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='depature',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
