# Generated by Django 3.1.2 on 2021-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat_booking',
            name='passenger',
        ),
        migrations.AddField(
            model_name='seat_booking',
            name='passenger',
            field=models.ManyToManyField(to='core.passenger'),
        ),
    ]
