# Generated by Django 3.1.2 on 2021-03-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210305_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trains')),
            ],
        ),
    ]
