# Generated by Django 3.1.2 on 2021-03-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seat_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat_booking',
            name='passenger',
        ),
        migrations.CreateModel(
            name='booking_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('seat_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seat_booking')),
            ],
        ),
    ]
