# Generated by Django 3.1.2 on 2021-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210306_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='seat_availability',
        ),
    ]
