# Generated by Django 3.1.2 on 2021-03-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210306_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trains',
            name='compartment_capacity',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='seats',
        ),
        migrations.CreateModel(
            name='train_charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_capacity', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trains')),
            ],
        ),
    ]
