# Generated by Django 3.1.2 on 2021-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210306_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_id',
            name='seat_no',
            field=models.IntegerField(null=True),
        ),
    ]
