# Generated by Django 3.1.2 on 2021-03-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_id_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat_booking',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.train_charts'),
        ),
    ]
