# Generated by Django 3.1.2 on 2021-03-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210307_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_booking_allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
            ],
        ),
    ]
